### ISSUE TITLE
Bug/Feature Request: Access violations not caught

### ISSUE THREAD

**Issue by jpalawaga** [KnpLabs/Gaufrette#131]
### Steps to reproduce:

Setup Gaufrette and configure a local adapter
Configure it to write to any file in any place (say, foobar.txt), with any text (say, 'hello world!') and tell set overwrite to true.

Before writing executing the script, give ownership to a user of higher permission than you. In Unix, you can probably give it to root and be okay (provided you're not running as root, for some reason).

Attempt to execute the script.
### What Happens:

PHP throws an permission denied error
### What Should Happen:

...not that. Since this is FS abstraction, it becomes really difficult to write a writable() function without breaking the whole idea behind FS abstraction. Throwing of some sort of an exception if the file cannot be written would be excellent.

I understand the lib is still under intensive development, but this is certainly something that would be really nice to have.

**Comment by PedroTroller** [comment]
Hi @jpalawaga. Thank you for your issue. Gaufrette has been abandoned for several years and we at KNPLabs are trying to revive our open-source projects. This issue is almost 10 years old now and I'm going to close it due to its inactivity. Feel free to reopen it if you need to.

For your information, @akerouanton gave an answer here https://github.com/KnpLabs/Gaufrette/pull/308#issuecomment-172317631
