### ISSUE TITLE
MD5 Support

### ISSUE THREAD

**Issue by estahn** [KnpLabs/Gaufrette#200]
Is there any support for MD5 available for the various adapters, e.g. local, S3, etc?

**Comment by PedroTroller** [comment]
Hi @estahn. Well, your issue is almost 10 years old now (oops). We're currently trying to revive our main open-source projects and will be more efficient in the future (hard to do worse).

To answer, the checksum has been implemented on the following adapters
 - https://github.com/KnpLabs/Gaufrette/blob/3cc396cae0f7c7d3f965e6b69d8fc546ffa0f94c/src/Gaufrette/Adapter/Local.php#L190
- https://github.com/KnpLabs/Gaufrette/blob/3cc396cae0f7c7d3f965e6b69d8fc546ffa0f94c/src/Gaufrette/Adapter/GridFS.php#L135
- https://github.com/KnpLabs/Gaufrette/blob/3cc396cae0f7c7d3f965e6b69d8fc546ffa0f94c/src/Gaufrette/Adapter/DoctrineDbal.php#L88

Don't hesitate to reopen this issue if you have other questions.

**Comment by estahn** [comment]
No worries, thanks for responding without just closing it. I have moved on to Golang :)

**Comment by PedroTroller** [comment]
Not because of us I hope... :crying_cat_face:
