### ISSUE TITLE
filesystem documentation

### ISSUE THREAD

**Issue by fcpauldiaz** [KnpLabs/Gaufrette#369]
The documentation provides a direct way to upload the files like this

```php
$filesystem->write($entity->getDocumentName(), $entity->getDocumentFile());
````
Where can I find the whole documentation to read the files?

**Comment by akovalyov** [comment]
You can use `$filesystem->read($filename);`. The example is in https://github.com/KnpLabs/Gaufrette#use-the-filesystem. However, I agree that docs are not the best yet.

**Comment by fcpauldiaz** [comment]
I found and API of another bundle. Can you @akovalyov  confirm me if the methods declared [here](http://flysystem.thephpleague.com/api/) work with this bundle?

**Comment by akovalyov** [comment]
@fcpauldiaz just to clarify that we are talking about the same things. Gaufrette is not a bundle. It is just a standalone PHP 5.3+ library for filesystem abstraction. If you need a Symfony2 bundle which integrates this lib into your project - you can use https://github.com/KnpLabs/KnpGaufretteBundle/.

Next, about the public API. `Flysystem` is *another* FS abstraction library written by https://github.com/thephpleague and I can't confirm anything about that just because I am not the right person to confirm things about it. Everything I can tell - it should work fine.

Using `Gaufrette` as a FS abstraction layer, you will use the public API of the class [https://github.com/KnpLabs/Gaufrette/blob/master/src/Gaufrette/Filesystem.php](Filesystem). which has the following methods:
```
* has($key)
* rename($sourceKey, $targetKey)
* get($key, $createIfMissing)
* write($key, $content, $shouldOverride)
* read($key)
* delete($key)
```
and more, which are known as working.

**Comment by fcpauldiaz** [comment]
Thanks for the correction and the info!
