### ISSUE TITLE
Php 5.6 trigggers "requires ext-ssh2 error"

### ISSUE THREAD

**Issue by alexgheorghiu** [KnpLabs/Gaufrette#372]
"herzult/php-ssh v1.1.1 requires ext-ssh2"

I tried to use your library on Win7 (php 5.6.16) and OpenSuse (php 5.6.1) but it failed on command 

__php ~/composer.phar require knplabs/gaufrette:0.3.*@dev__

with messages like 

__herzult/php-ssh dev-master requires ext-ssh2 * -> the requested PHP extension ssh2 is missing from your system.__

After a little bit of study I discovered that ssh2 is not available for Php5.6 which makes me wonder what should I do. 

My project is migrating to 5.6 and it would be nice to use your library....

**Comment by alexgheorghiu** [comment]
Ok,  I was able to overcome this issue by downloading a PHP build from https://www.apachelounge.com/viewtopic.php?t=6123 and use (copy) the ssh2.dll from there.

**Comment by akovalyov** [comment]
@alexgheorghiu well, that's strange. (We're suggesting)[https://github.com/KnpLabs/Gaufrette/blob/master/composer.json#L47] `herzult/php-ssh`, but not requiring it, so I assume that you have explicitly defined that dependency in your `composer.json` file. 
I assume that the recommended way to install ssh2 extension is using `PECL`.

However, this issue is not related to Gaufrette. So, closing.
